version: 1.0.{build}

# environment variables
environment:
  GithubEmail: johnny_reilly@hotmail.com
  GithubUsername: johnnyreilly
  GithubPersonalAccessToken:
    secure: T4M/N+e/baksVoeWoYKPWIpfahOsiSFw/+Zc81VuThZmWEqmrRtgEHUyin0vCWhl

branches:
  only:
    - master

# scripts to run before build
before_build:
- cmd: >-
    npm install

    npm run bower-install


build_script:
- cmd: >-
    npm run build-release

before_test:
- ps: >-
    write-host "Present working directory: $($pwd)"

    $testsuites = [xml](get-content .\test-results\*.xml)

    $anyFailures = $FALSE

    foreach ($testsuite in $testsuites.testsuite) {

        write-host " $($testsuite.name)"

        foreach ($testcase in $testsuite.testcase){

            $failed = $testcase.failure

            $time = [decimal]$testsuite.time * 1000 # from seconds to milliseconds

            if ($failed) {

                write-host "Failed   $($testcase.name) $($testcase.failure.message)"

                Add-AppveyorTest $testcase.name -Outcome Failed -FileName $testsuite.name -ErrorMessage $testcase.failure.message -Duration $time

                $anyFailures = $TRUE

            }

            else {

                write-host "Passed   $($testcase.name)"

                Add-AppveyorTest $testcase.name -Outcome Passed -FileName $testsuite.name -Duration $time

            }

        }

    }

    if ($anyFailures -eq $TRUE){

        write-host "Failing build as there are broken tests"

        $host.SetShouldExit(1)

    }

deploy_script:
- ps: ./pushStatic.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:APPVEYOR_REPO_NAME
