version: 1.0.{build}
os: Visual Studio 2015 CTP

# environment variables
environment:
  GithubEmail: johnny_reilly@hotmail.com
  GithubUsername: johnnyreilly
  GithubPersonalAccessToken:
    secure: T4M/N+e/baksVoeWoYKPWIpfahOsiSFw/+Zc81VuThZmWEqmrRtgEHUyin0vCWhl

branches:
  only:
    - master

# scripts to run before build
before_build:
- cmd: >-
    npm install

build_script:
- cmd: >-
    npm run build-release

deploy_script:
- ps: ./pushStatic.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken
